### PR TITLE
Add `conan package` abstractions and related documentation.

### PR DESCRIPTION
**Pull request by Tomcat-42**
Hello @awakecoding,

I've created some abstractions around the `conan package` command. Also, I've improved the Readme and added some doc comments.

I think now one can use *conan-rs* to fully integrate a rust crate into a c++/conan codebase.  

What is your oppinion on making a new release of *conan-rs*

Waiting for your feedback,
Pablo.

### CODE REVIEW

**Review by awakecoding — APPROVED** [review]

**Comment by awakecoding** [comment]
@Tomcat-42 I can make a release in crates.io whenever you feel it is ready, just let me know if the latest master is good to go

**Comment by Tomcat-42** [comment]
We can make a release now.

**Comment by awakecoding** [comment]
there you go, it is released now: https://crates.io/crates/conan/0.4.1

**Comment by Tomcat-42** [comment]
Thanks very much @awakecoding 

:partying_face:

**Pull request merged**
